# Generated by Django 4.1.3 on 2023-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ffff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
